name: Deploy to GitHub Pages (web only)
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Se já tiver os arquivos prontos em web/, copia para docs/
      - name: Prepare docs
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r web/* docs/

      - name: Commit docs if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs
            git commit -m "Update docs from web on $(date -Iseconds)"
            git push
          fi
